#!/bin/sh
#
# chkconfig: 345 80 20
# description: Handle server
# processname: handle-server
#
# P@ Aug '08
if [ -x /etc/rc.d/init.d/functions ]; then
. /etc/rc.d/init.d/functions
fi

JAVA="/usr/bin/java"
PROJ_DIR="/opt/handle-server"
SERVER="svr_1"

start() {
  echo -n "Starting handle server: "

  ${JAVA} -cp ${PROJ_DIR}/bin/handle.jar:${PROJ_DIR}/bin/mysql-connector-java-3.1.7-bin.jar net.handle.server.Main ${PROJ_DIR}/${SERVER} >> /var/log/handle-server/${SERVER}.log 2>&1 &

  RETVAL=$?

  return $RETVAL
}

stop() {
  echo -n "Stopping handle server: "

  ps -ef | grep "[h]andle-server" | awk '{print $2}' | xargs kill

  RETVAL=$?

  return $RETVAL
}

status() {
  ps -ef | grep "[h]andle-server"
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status
        ;;
  restart)
  stop
  sleep 2
  start
  ;;
  *)
  echo "Usage: handle-server {start|stop|restart|status}"
  exit 1
esac

exit $RETVAL
